// src/lib/components/FileUpload.svelte
<script lang="ts">
	import { Upload } from 'lucide-svelte';
	import { cn } from '$lib/utils/cn';

	interface Props {
		onFileUpload: (file: File) => void;
	}

	let { onFileUpload }: Props = $props();

	let fileInputRef = $state<HTMLInputElement>();
	let isDragging = $state(false);
	let dragCounter = 0;

	function handleClick() {
		fileInputRef?.click();
	}

	function handleFileChange(event: Event) {
		const input = event.target as HTMLInputElement;
		const file = input.files?.[0];
		if (file) {
			onFileUpload(file);
			if (fileInputRef) {
				fileInputRef.value = '';
			}
		}
	}

	function handleDrag(e: DragEvent) {
		e.preventDefault();
		e.stopPropagation();
	}

	function handleDragIn(e: DragEvent) {
		e.preventDefault();
		e.stopPropagation();
		dragCounter += 1;
		if (e.dataTransfer?.items && e.dataTransfer.items.length > 0) {
			isDragging = true;
		}
	}

	function handleDragOut(e: DragEvent) {
		e.preventDefault();
		e.stopPropagation();
		dragCounter -= 1;
		if (dragCounter === 0) {
			isDragging = false;
		}
	}

	function handleDrop(e: DragEvent) {
		e.preventDefault();
		e.stopPropagation();
		isDragging = false;
		dragCounter = 0;
		const file = e.dataTransfer?.files[0];
		if (file && file.type === 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') {
			onFileUpload(file);
		}
	}

	function handlePaste(e: ClipboardEvent) {
		const items = e.clipboardData?.items;
		if (items) {
			for (let i = 0; i < items.length; i++) {
				if (items[i].kind === 'file') {
					const file = items[i].getAsFile();
					if (file && file.type === 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') {
						onFileUpload(file);
						e.preventDefault();
						break;
					}
				}
			}
		}
	}

	$effect(() => {
		window.addEventListener('paste', handlePaste);
		return () => window.removeEventListener('paste', handlePaste);
	});
</script>

<div class="mb-12">
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class={cn(
			'flex min-h-[200px] cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-border bg-card p-6 text-card-foreground shadow-sm transition-colors hover:border-primary hover:bg-primary/5',
			isDragging && 'border-primary bg-primary/10'
		)}
		onclick={handleClick}
		onkeydown={(e) => e.key === 'Enter' && handleClick()}
		ondragenter={handleDragIn}
		ondragleave={handleDragOut}
		ondragover={handleDrag}
		ondrop={handleDrop}
		role="button"
		tabindex="0"
	>
		<div class="flex flex-col items-center gap-2 text-center">
			<Upload class="size-10 text-muted-foreground" />
			<p class="text-sm text-muted-foreground">
				Drop XLSX file here, click to select, or paste from clipboard
			</p>
			<p class="text-xs text-muted-foreground">
				Only .xlsx files are supported
			</p>
		</div>
		<input type="file" bind:this={fileInputRef} onchange={handleFileChange} accept=".xlsx" class="hidden" />
	</div>
</div>

// src/components/FileUpload.tsx
import { useRef, useState, useEffect, useCallback } from 'react';

import { Upload } from 'lucide-react';

import { Card } from '@components/ui/card';
import { cn } from '@utils/cn';

interface FileUploadProps {
  onFileUpload: (file: File) => void;
}

const FileUpload = ({ onFileUpload }: FileUploadProps) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isDragging, setIsDragging] = useState(false);
  const dragCounter = useRef(0);

  const handleClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      onFileUpload(file);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const handleDrag = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
  };

  const handleDragIn = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    dragCounter.current += 1;
    if (event.dataTransfer.items && event.dataTransfer.items.length > 0) {
      setIsDragging(true);
    }
  };

  const handleDragOut = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    dragCounter.current -= 1;
    if (dragCounter.current === 0) {
      setIsDragging(false);
    }
  };

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragging(false);
    dragCounter.current = 0;
    const file = event.dataTransfer.files[0];
    if (
      file &&
      file.type ===
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ) {
      onFileUpload(file);
    }
  };

  const handlePaste = useCallback(
    (event: ClipboardEvent) => {
      const items = event.clipboardData?.items;
      if (items) {
        for (let i = 0; i < items.length; i += 1) {
          if (items[i].kind === 'file') {
            const file = items[i].getAsFile();
            if (
              file &&
              file.type ===
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            ) {
              onFileUpload(file);
              event.preventDefault();
              break;
            }
          }
        }
      }
    },
    [onFileUpload],
  );

  useEffect(() => {
    window.addEventListener('paste', handlePaste);
    return () => {
      window.removeEventListener('paste', handlePaste);
    };
  }, [handlePaste]);

  return (
    <div className="mb-12">
      <Card
        onClick={handleClick}
        className={cn(
          'flex min-h-[200px] cursor-pointer flex-col items-center justify-center border-2 border-dashed p-6 transition-colors hover:border-primary hover:bg-primary/5',
          {
            'border-primary bg-primary/10': isDragging,
            'border-border': !isDragging,
          },
        )}
        onDragEnter={handleDragIn}
        onDragLeave={handleDragOut}
        onDragOver={handleDrag}
        onDrop={handleDrop}
      >
        <div className="flex flex-col items-center gap-2 text-center">
          <Upload className="size-10 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            Drop XLSX file here, click to select, or paste from clipboard
          </p>
          <p className="text-xs text-muted-foreground">
            Only .xlsx files are supported
          </p>
        </div>
        <input
          type="file"
          ref={fileInputRef}
          onChange={handleFileChange}
          accept=".xlsx"
          className="hidden"
        />
      </Card>
    </div>
  );
};

export default FileUpload;
