// src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { Moon, Sun, Monitor } from 'lucide-svelte';
	import Button from './ui/Button.svelte';
	import DropdownMenu from './ui/DropdownMenu.svelte';
	import DropdownMenuItem from './ui/DropdownMenuItem.svelte';
	import { themeStore } from '$lib/stores/themeStore.svelte';

	let theme = $derived(themeStore.theme);
	let resolvedTheme = $derived(themeStore.resolvedTheme);
</script>

<DropdownMenu>
	{#snippet trigger()}
		<Button variant="ghost" size="icon" class="size-9">
			<Sun class="size-[1.2rem] rotate-0 scale-100 transition-all {resolvedTheme === 'dark' ? '-rotate-90 scale-0' : ''}" />
			<Moon class="size-[1.2rem] rotate-90 scale-0 transition-all {resolvedTheme === 'dark' ? 'rotate-0 scale-100' : ''}" />
			<span class="sr-only">Toggle theme</span>
		</Button>
	{/snippet}
	{#snippet children()}
		<DropdownMenuItem onclick={() => themeStore.setTheme('light')}>
			<Sun class="mr-2 size-4" />
			Light
			{#if theme === 'light'}
				<span class="ml-auto text-xs text-primary">●</span>
			{/if}
		</DropdownMenuItem>
		<DropdownMenuItem onclick={() => themeStore.setTheme('dark')}>
			<Moon class="mr-2 size-4" />
			Dark
			{#if theme === 'dark'}
				<span class="ml-auto text-xs text-primary">●</span>
			{/if}
		</DropdownMenuItem>
		<DropdownMenuItem onclick={() => themeStore.setTheme('system')}>
			<Monitor class="mr-2 size-4" />
			System
			{#if theme === 'system'}
				<span class="ml-auto text-xs text-primary">●</span>
			{/if}
		</DropdownMenuItem>
	{/snippet}
</DropdownMenu>

// src/components/ThemeToggle.tsx
import { Moon, Sun, Monitor } from 'lucide-react';

import { Button } from '@components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@components/ui/dropdown-menu';
import { useThemeStore } from '@store/themeStore';

export function ThemeToggle() {
  const { theme, setTheme } = useThemeStore();

  return (
    <DropdownMenu modal={false}>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="size-9">
          <Sun className="size-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
          <Moon className="absolute size-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
          <span className="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => setTheme('light')}>
          <Sun className="mr-2 size-4" />
          Light
          {theme === 'light' && (
            <span className="ml-auto text-xs text-primary">●</span>
          )}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme('dark')}>
          <Moon className="mr-2 size-4" />
          Dark
          {theme === 'dark' && (
            <span className="ml-auto text-xs text-primary">●</span>
          )}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme('system')}>
          <Monitor className="mr-2 size-4" />
          System
          {theme === 'system' && (
            <span className="ml-auto text-xs text-primary">●</span>
          )}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
